[tool.poetry]
name = "latex-doc-generator"
version = "0.2.0"
description = "Cloud-Native LaTeX Compilation Service"
authors = ["MordXD <kotkinegor78@gmail.com>"]
readme = "README.md"
license = "MIT"
packages = [{include = "backend"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.104.1"
uvicorn = {extras = ["standard"], version = "^0.24.0"}
python-dotenv = "^1.0.0"
pydantic = "^2.5.0"
pydantic-settings = "^2.0.0"
websockets = "^12.0"
python-multipart = "^0.0.6"
httpx = "^0.28.1"
# RabbitMQ
faststream = {extras = ["rabbit"], version = "^0.5.15"}
aio-pika = "^9.4.1"
# Redis & S3
redis = "^5.0.1"
boto3 = "^1.34.0"
botocore = "^1.34.0"
prometheus-fastapi-instrumentator = "^6.1.0"
prometheus-client = "^0.19.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-asyncio = "^0.21.1"
black = "^23.11.0"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.main.api"