apiVersion: v1
kind: Secret
metadata:
  name: latex-secrets
  namespace: latex-app
type: Opaque
stringData:
  # В продакшене используйте External Secrets Operator или Sealed Secrets
  S3_ACCESS_KEY: "minioadmin"
  S3_SECRET_KEY: "minioadmin"